@prefix = http://localhost:8080
@apiPrefix = {{prefix}}/api
@jsonHeader = Content-Type: application/json

### index
GET http://localhost:8080/

### signup
POST {{prefix}}/signup
{{jsonHeader}}

{
    "fullname": "zhangsan",
    "email": "zhangsan@chat.rs",
    "password": "123456"
}

### signin
# @name signin
POST {{prefix}}/signin
{{jsonHeader}}

{
    "email": "zhangsan@chat.rs",
    "password": "123456"
}

### list chat
GET {{apiPrefix}}/chat
Authorization: Bearer {{signin.response.body.$.token}}

### create chat
POST {{apiPrefix}}/chat
{{jsonHeader}}

### update chat
PATCH {{apiPrefix}}/chat/1
{{jsonHeader}}

### send message
POST {{apiPrefix}}/chat/1
{{jsonHeader}}
