server:
  host: 0.0.0.0
  port: 8080
  db_url: postgres://postgres:postgres@localhost/chat-dev
auth:
  sk: |
    -----BEGIN PRIVATE KEY-----
    MC4CAQAwBQYDK2VwBCIEIGdNL9UA4NqKx4A+2VHy0AnjIL6HqMLMyRDDTjGXKWZm
    -----END PRIVATE KEY-----
  pk: |
    -----BEGIN PUBLIC KEY-----
    MCowBQYDK2VwAyEAh3m+6a6m4gDGlAFnH78GuU3lNfu3vjy0VErVrDVKghw=
    -----END PUBLIC KEY-----
