[package]
name = "chat-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
argon2 = "0.5.3"
# argon2 = { version = "0.5", features = ["std"] }
axum = { workspace = true }
chrono = { workspace = true }
jsonwebtoken = "9.3.0"
# jwt-simple = "0.12"
serde = { workspace = true }
serde_yaml = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
# http-body-util = "0.1.1"
# sqlx-db-tester = "0.4.0"
